/**
 * 
 */
package solutions;

import java.util.Scanner;

/**
 * @author Dhawal.Verma
 * 
 * Each new term in the Fibonacci sequence 
 * is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence 
 * whose values do not exceed n, find the sum of the even-valued terms.
 *
 */
public class P2_SumOfEvenFibonacciNumbers
{
	public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int t = in.nextInt();
        for(int a0 = 0; a0 < t; a0++){
            long n = in.nextLong();
            System.out.println(sum(n));
        }
    }
	
	static long sum(long n)
	{
		long sum = 0;
		
		
		
		return sum;
	}
}
